config/routes.rb
Rails.application.routes.draw do
  post '/users/:user_id/services/:service_id/handies/:id/ads/create', to: 'ads#create', as: 'ad_create'
  post '/create', to:'users#create', as: 'create'
  resources :users do
    # post '/ads', to: 'ads#create', as: 'ads'
    #post 'users/:id/ads/:id' to: 'user#update'
    resources :ads
    resources :services do
      resources :handies
    end
    resources :handy_services
    resources :handies

  end

  get '/welcome', :to => 'users#welcome'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :handy

  def customer
    user
  end

  # def contractor
  #   service.handies.each do |handy|
  #     handy
  #   end
  # end

  def job
    service
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/handy.rb
class Handy < ApplicationRecord
  has_many :handy_services
  has_many :services, through: :handy_services
  has_many :ads
  has_many :users, through: :ads

  

end

app/models/handy_service.rb
class HandyService < ApplicationRecord
  belongs_to :handy
  belongs_to :service

  #valting that we can't create the same job for one handyman

def all_handy_guys
  self.handy
end

end

app/models/service.rb
class Service < ApplicationRecord
  has_many :handy_services
  has_many :handies, through: :handy_services
  has_many :ads
  has_many :users, through: :ads

  def workers
    handies
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ads
  has_many :services, through: :ads
  has_many :handies, through: :ads

  #validates :username, uniqueness: true

  # def serve
  #   services.each do |service|
  #     service
  #   end
  # end

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

   # def index
   #   @ads = Ad.all
   #   @users = User.all
   # end

  def show
    @ad = Ad.find(params[:id])
    #@user = User.find(params[:user_id])
    #@service = Service.find(params[:service_id])
    # @handyservices = HandyService.all
    # @hps = HandyService.all
    @ads = Ad.all

    @services = Service.all
    @handyservice = HandyService.new
    @handyservices = HandyService.all
    @handy = Handy.new
    @handies = Handy.all
    #@handyfind = Handy.find(params[:id])
    @user = User.find(params[:user_id])
  end






  def create
    @ad = Ad.new(user_id: params[:user_id], service_id: params[:service_id], handy_id: params[:id])
    @ad.save
    # byebug
    @user = User.find(params[:user_id])
    #@service = Service.find(params[:service_id])

    redirect_to user_ad_path(@user, @ad)
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    @ad.update(add_update_params)
    redirect_to user_ad_path
  end

  private

  def ad_params
    params.permit(:user_id, :service_id, :id, :rating)
  end

  def add_update_params
    params.require("/users/#{params[:id]}").permit(:rating)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/handies_controller.rb
class HandiesController < ApplicationController

  def index
    @handies = Handy.all
  end

  def show
    @handy = Handy.find(params[:id])
    @services = Service.all
    @handyservice = HandyService.new
    @handyservices = HandyService.all
    @user = User.find(params[:user_id])
    @service = Service.find(params[:service_id])
  end
end

app/controllers/handy_services_controller.rb
class HandyServicesController < ApplicationController

  def new
    @handyservice = HandyService.new
  end

  def create
    @handyservice = HandyService.new(handyservice_params)
    @handyservice.save
    @handy = Handy.find(handyservice_params[:handy_id])
    #render :new
    redirect_to user_path(@handy)
  end

  private

  def handyservice_params
    params.require(:handy_service).permit(:handy_id, :service_id)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all
    @user = User.find(params[:user_id])
  end

  def show
    @service = Service.find(params[:id])
    @user = User.find(params[:user_id])
  end

  private

   def service_params
     params.require(:service).permit(:name, :id)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @services = Service.all
    #@service = Service.find(service_params[:id])
    # @ad = Ad.new
    # @ads = Ad.all
    # @handies = Handy.all
    #@handy = Handy.find(params[:id])
  end

  # def welcome
  #   @user = User.find(params[:id])
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     @user.save
    redirect_to @user

  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/handies_helper.rb
module HandiesHelper
end

app/helpers/handy_prsons_helper.rb
module HandyPrsonsHelper
end

app/helpers/handy_services_helper.rb
module HandyServicesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ads/show.html.erb
<div id="content">
  <h1>Service Call</h1>
<%taco = "🌮"%>

<ul>
  <li>Customer: <%= @ad.customer.name %></li>
  <li>Work Done: <%= @ad.job.name %></li>
  <li>Handy Person: <%= @ad.handy.name %></li>
  <% if @ad.rating != nil %>
  <li>Rating: <%= taco * @ad.rating %></li>
  <%end%>

</ul>

<%= form_for user_path(@ad), method: :patch do |f| %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: 1..5 %>
  <%= f.submit 'Rate'%>
<% end %>


<ul class="btn" align="center"><%= link_to 'Profile Page', user_path(@user),  :method => "get" %></ul>
</div>

app/views/handies/index.html.erb
<h1>HandyPeople</h1>
<ul>
  <% @handies.each do |handy| %>
    <li><%= link_to handy.name, handy_path(handy) %></li>
  <% end %>
</ul>

app/views/handies/show.html.erb
<div id="content">
  <% taco = "🌮" %>
<h1>Handy Person</h1>
<h2>Name: <%= @handy.name %></h2>
<h2>Username: <%= @handy.username %></h2>

<% ratings = [] %>
<% total_rating = 0 %>
<% all_ratings = [] %>
<% @handy.ads.each do |ad| %>
   <% ratings << ad.rating %>
   <% ratings.compact.each do |rating| %>
   <% total_rating += rating %>
   <% all_ratings << rating %>
 <% end %>
<% end %>

<% if all_ratings.length != 0 %>
<% rating = total_rating / all_ratings.length %>
<h2>Average Rating: <%= taco * rating %></h2>
<h3>Services Provides</h3>
<ul>
  <% @handy.services.each do |work| %>
    <li><%=  work.name %></li>
  <% end %>
  <% end %>
</ul>


<li class="btn"  align="center"><%= link_to 'Request Service', ad_create_path, method: :post %></li>

</div>





<%# form_for [:user, @handyservice] do |f| %>
  <%# f.hidden_field :handy_id, value: @handy.id %>
  <%# f.collection_select :service_id, @services, :id, :name %>
  <%# f.submit %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HandyPeople</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




    <div id="header">
      <a id="logo">HandyPeople</a>
      <ul id="menu">
        <% if @user %>
        <li><h4><%= link_to "Services", user_services_path(@user) %></h4></li>
        <li><h4><%= link_to "Profile", user_path(@user) %></h4></li>
        <li><h4><%= link_to 'Logout' %></h4></li>
        <li><h4><%= link_to 'Back', :back %></h4></li>
        <% else %>

      <% end %>
      </ul>
    </div>


    <%= yield %>
  </body>
</html>

app/views/services/index.html.erb
<div id="content">
<h1>Services</h1>
<ul>
  <% @services.each do |service| %>
    <li class="btn"  align="center"><%= link_to service.name, user_service_path(@user, service) %></li>
  <% end %>
</ul>
</div>

app/views/services/show.html.erb
<div id="content">
<h1>Service</h1>
<h2><%= @service.name %></h2>
<h3>Suggested Handies</h3>
<ol>
  <% @service.handies.each do |handy| %>
    <li class="btn"  align="center"><%= link_to handy.name, user_service_handy_path(@user, @service, handy) %></li>
    <% end %>
</ol>
<br>
<br>
</div>

app/views/users/show.html.erb
<div id="content">
<h1>Profile</h1>
<h2>Name: <%= @user.name %></h2>
<h2>Username: <%= @user.username %></h2>
<%taco = "🌮"%>

<h3>Services Calls</h3>
<ul>
  <% @user.ads.each do |ad| %>
  <%= link_to ad.service.name, user_ad_path(@user, ad) %>
    <br>
  <%= ad.handy.name %>
  <br>
    <% if ad.rating != nil %>

  Tacos: <%= taco * ad.rating %>
    <br>
  <% else %>
  <%end%>
  <br>
  <% end %>
  </ul>
  <br>

<ul class="btn"  align="center"><%= link_to 'Request Service', user_services_path(@user) %></ul>

</div>

app/views/users/welcome.html.erb
<%# form_for @user do |f| %>
  <%# f.label :name %>
  <%# f.text_field :name %>
<%# end %>
<div id="content">
<ul>
  <h1>Create Account</h1>
  <%= form_for User.new, :url => create_path, :method => :post do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :username %>
    <%= f.text_field :username %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.submit 'Create Account' %>

  <% end %>
</ul>
</div>